### ISSUE TITLE
Panning Error with NDScatter Graph

### ISSUE THREAD

**Issue by maegul** [tridesclous/tridesclous#106]
I think this may have been mentioned already in https://github.com/tridesclous/tridesclous/issues/57#issue-313235639

It does not seem possible to pan the ndscatter cluster graph.

When I attempt to do so by clicking and dragging the axes, the error below is logged.

The GUI has impressed me, but this inability to pan the cluster graph is probably the one thing that I feel like is unfortunate in the workings of the catalogue viewer.

Also, from my experience with plotqtgraph, I believe panning is the default behaviour for the graphs there?  I hope this is a bug and not design choice.

Nonetheless, thanks for your tool ... like I said ... impressed ... keep up the good work!

[00:27:27]  Error sending drag event:

    |==============================>>
    |  Traceback (most recent call last):
    |    File "/Users/errollloyd/anaconda/envs/ephs/bin/tdc", line 11, in <module>
    |      sys.exit(main())
    |    File "/Users/errollloyd/anaconda/envs/ephs/lib/python3.6/site-packages/tridesclous/scripts/tdc.py", line 66, in main
    |      open_mainwindow()
    |    File "/Users/errollloyd/anaconda/envs/ephs/lib/python3.6/site-packages/tridesclous/scripts/tdc.py", line 29, in open_mainwindow
    |      app.exec_()
    |    File "/Users/errollloyd/anaconda/envs/ephs/lib/python3.6/site-packages/pyqtgraph/widgets/GraphicsView.py", line 368, in mouseMoveEvent
    |      QtGui.QGraphicsView.mouseMoveEvent(self, ev)
    |    File "/Users/errollloyd/anaconda/envs/ephs/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 183, in mouseMoveEvent
    |      if self.sendDragEvent(ev, init=init):
    |    File "/Users/errollloyd/anaconda/envs/ephs/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 299, in sendDragEvent
    |      debug.printExc("Error sending drag event:")
    |    --- exception caught here ---
    |    File "/Users/errollloyd/anaconda/envs/ephs/lib/python3.6/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 297, in sendDragEvent
    |      item.mouseDragEvent(event)
    |    File "/Users/errollloyd/anaconda/envs/ephs/lib/python3.6/site-packages/pyqtgraph/graphicsItems/AxisItem.py", line 1069, in mouseDragEvent
    |      return self.linkedView().mouseDragEvent(event, axis=1)
    |  TypeError: mouseDragEvent() got an unexpected keyword argument 'axis'
    |==============================<<

**Comment by samuelgarcia** [comment]
Thanks for feedback.

I will fix it.
I get lot of same feed back like this about this NDScatter.

**Comment by samuelgarcia** [comment]
I am back here (a bit).

I will have a problem to make the drag and drop zoom like in standard pyqtgraph in ndscatter because the drag and drop is used internally by the lasso selection.

What can be done is when using the wheel mouse zoom the center could be a the mouse position and not the (0, 0) position. Would this be OK as behavior ?

**Comment by maegul** [comment]
@samuelgarcia That sounds like a very good option to me!
