### ISSUE TITLE
TDT  init dataset fails, neo cannot parse header

### ISSUE THREAD

**Issue by matthewperkins** [tridesclous/tridesclous#123]
Traceback (most recent call last):
  File "/home/matthew/.virtualenvs/tdc/lib/python3.6/site-packages/tridesclous/gui/initializedatasetwindow.py", line 168, in validate_step
    self.display_step('mk_chan_grp')
  File "/home/matthew/.virtualenvs/tdc/lib/python3.6/site-packages/tridesclous/gui/initializedatasetwindow.py", line 105, in display_step
    channel_names = self.datasource_class(**source_params).get_channel_names()
  File "/home/matthew/.virtualenvs/tdc/lib/python3.6/site-packages/tridesclous/datasource.py", line 190, in __init__
    rawio.parse_header()
  File "/home/matthew/.virtualenvs/tdc/lib/python3.6/site-packages/neo/rawio/baserawio.py", line 151, in parse_header
    self._parse_header()
  File "/home/matthew/.virtualenvs/tdc/lib/python3.6/site-packages/neo/rawio/tdtrawio.py", line 142, in _parse_header
    self._global_t_start = self._seg_t_starts[0]
IndexError: list index out of range
Aborted (core dumped)

**Comment by matthewperkins** [comment]
`[Traceback (most recent call last):
  File "/home/matthew/.virtualenvs/tdc/lib/python3.6/site-packages/tridesclous/gui/initializedatasetwindow.py", line 168, in validate_step
    self.display_step('mk_chan_grp')
  File "/home/matthew/.virtualenvs/tdc/lib/python3.6/site-packages/tridesclous/gui/initializedatasetwindow.py", line 105, in display_step
    channel_names = self.datasource_class(**source_params).get_channel_names()
  File "/home/matthew/.virtualenvs/tdc/lib/python3.6/site-packages/tridesclous/datasource.py", line 190, in __init__
    rawio.parse_header()
  File "/home/matthew/.virtualenvs/tdc/lib/python3.6/site-packages/neo/rawio/baserawio.py", line 151, in parse_header
    self._parse_header()
  File "/home/matthew/.virtualenvs/tdc/lib/python3.6/site-packages/neo/rawio/tdtrawio.py", line 142, in _parse_header
    self._global_t_start = self._seg_t_starts[0]
IndexError: list index out of range
Aborted (core `dumped)](url)`

**Comment by matthewperkins** [comment]
Also, pretty cool project!

**Comment by Gittinator** [comment]
I'm having the same error
