### ISSUE TITLE
CatalogueConstructor on existing sorted data incomplete

### ISSUE THREAD

**Issue by subhacom** [tridesclous/tridesclous#139]
When trying to create a `CatalogueWindow` on a `CatalogueConstructor` based on an existing data directory (after already running `find_clusters` in a separate session), this exception occurs:
```
DataIO <id: 42866504>
  workdir: D:/user_data/spike_sorting/2019_11_26/tdc_all
  sample_rate: 20000.0
  total_channel: 12
  channel_groups: 0 (3ch), 1 (4ch), 2 (4ch)
  nb_segment: 240
Traceback (most recent call last):
  File "run_tdc_catview.py", line 24, in <module>
    win = tdc.CatalogueWindow(cat_t1)
  File "C:\Users\User\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\gui\cataloguewindow.py", line 37, in __init__
    self.controller = CatalogueController(catalogueconstructor=catalogueconstruc
tor)
  File "C:\Users\User\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\gui\cataloguecontroller.py", line 30, in __init__
    self.init_plot_attributes()
  File "C:\Users\User\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\gui\cataloguecontroller.py", line 40, in init_plot_attributes
    self.cluster_visible = {k:i<20 for i, k  in enumerate(self.cluster_labels)}
  File "C:\Users\User\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\gui\cataloguecontroller.py", line 102, in cluster_labels
    return self.cc.clusters['cluster_label']
TypeError: 'NoneType' object is not subscriptable
```

Turns out that although `CatalogueConstructor` is supposed to have some persistent properties, creating one based on an existing sorting directory does not load the `catalogue` dict. One can explicitly load and assign the catalogue using `catalogue_constructor.catalogue = dataio.load_catalogue(chang_grp=N)`.

A better solution will be to load the catalogue automatically when a CatalogueConstructor is created based on existing sorting directory. Essentially, users should be able to save the state in the middle of sorting and start another session and pick up the work where they left it.

**Comment by samuelgarcia** [comment]
Normaly everything is totally persistent.
So you should able to open, close, re run many times.
But you need to have all steps before.
If you don't want clustering choose OneCluster.

The CatalogueConstructor.catalogue assignment should have no effect.

**Comment by subhacom** [comment]
That's the problem. I create a CatalogueConstructor as follows:
```python
cc = tdc.CatalogueConstructor(dataio=dataio, chan_grp=0, name='tetrode_1')
...
cc.find_clusters(method='dbscan', eps=6.7)
```
Do I need something more to save the cluster information? 
After this I run another script that has
```python
dataio = tdc.DataIO(dirname=target_dir)
# dataio.set_data_source(type='RawData', filenames=file_paths, dtype='int16', total_channel=len(channels), sample_rate=fs)
print(dataio)
cat_t1 = tdc.CatalogueConstructor(dataio, chan_grp=0, name='tetrode_1')
# cat_t1.set_global_params(chunksize=1024, mode='dense')
# cat_t1.catalogue = dataio.load_catalogue(chan_grp=0)
pprint(cat_t1.catalogue)
```
and get this exception:
```
DataIO <id: 35989320>
  workdir: D:/subhasis_data/spike_sorting/2019_11_26/tdc_all_1
  sample_rate: 20000.0
  total_channel: 12
  channel_groups: 0 (3ch), 1 (4ch), 2 (4ch)
  nb_segment: 60
Traceback (most recent call last):
  File "run_tdc_catview.py", line 22, in <module>
    pprint(cat_t1.catalogue)
AttributeError: 'CatalogueConstructor' object has no attribute 'catalogue'

```

**Comment by samuelgarcia** [comment]
The catalogue constructor have many attribute to help to construct the catalogue.
(all_peaks, some_peaks_index, some_waveforms, some_features, clusters, ...)
Theses attributes are when memory_mode='memmap' (by default) are persistent on disk so viewer can rely on then.

At the end of the process catalogueconstrutor.make_catalogue_for_peeler basically make a copy of a subset of theses attribute usefull for the peeler. This step must be call explicitly always when there is a modification in the catalogueconstructor.

CatalogueConstructor.catalogue is more or less for nothing.

If you hack some view please rely on cataloguecontroller wich is a layer on top cataloguecontroller than expose some attributes reformated for view. This is by design so that view are shared between cataloguewindow and peeler window (there is also a peelercontroller).

I hope to be clear. I should enhance the doc about that.
