### ISSUE TITLE
CatalogueWindow raises exception when creating new cluster from selected points

### ISSUE THREAD

**Issue by subhacom** [tridesclous/tridesclous#141]
When I try to create a new cluster by selecting a group of points in the ndscatter pane in CatalogueWindow, it raises exception on the newly created cluster (here I had 4 clusters, and created no. 5, which seems to generate an inconsistent state.
```
Traceback (most recent call last):
  File "/home/subha/.conda/envs/spike/lib/python3.6/site-packages/tridesclous/gui/peaklists.py", line 216, in make_new_cluster
    self.controller.change_spike_label(self.controller.spike_selection, max(self.controller.cluster_labels)+1)
  File "/home/subha/.conda/envs/spike/lib/python3.6/site-packages/tridesclous/gui/cataloguecontroller.py", line 212, in change_spike_label
    self.cc.change_spike_label(mask, label)
  File "/home/subha/.conda/envs/spike/lib/python3.6/site-packages/tridesclous/catalogueconstructor.py", line 1264, in change_spike_label
    self.add_one_cluster(label) # this also compute centroid
  File "/home/subha/.conda/envs/spike/lib/python3.6/site-packages/tridesclous/catalogueconstructor.py", line 1079, in add_one_cluster
    new_arr = np.zeros((arr.shape[0]+1, arr.shape[1], arr.shape[2]), dtype=arr.dtype)
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/home/subha/.conda/envs/spike/lib/python3.6/site-packages/tridesclous/gui/traceviewer.py", line 227, in on_combo_seg_changed
    self.change_segment(s)
  File "/home/subha/.conda/envs/spike/lib/python3.6/site-packages/tridesclous/gui/traceviewer.py", line 211, in change_segment
    self.refresh()
  File "/home/subha/.conda/envs/spike/lib/python3.6/site-packages/tridesclous/gui/traceviewer.py", line 243, in refresh
    self.seek(self.time_by_seg[self.seg_num])
  File "/home/subha/.conda/envs/spike/lib/python3.6/site-packages/tridesclous/gui/traceviewer.py", line 435, in seek
    if not self.controller.cluster_visible[k]: continue
KeyError: 5
```

**Comment by subhacom** [comment]
Sorry, this was with version 1.3.0, it is fixed in the current development version.

**Comment by samuelgarcia** [comment]
Thank you.
