### ISSUE TITLE
Reference checks hamper combining scripting with GUI for data analysis

### ISSUE THREAD

**Issue by subhacom** [tridesclous/tridesclous#142]
When interactively trying to explore spike sorting data in Python, accessing the attributes of in CatalogueConstructor often results in exceptions later when operating on the GUI (CatalogueWindow). It appears that there is a lot of places in the code where these attributes are checked for reference count. Is there a way to avoid this?
```python

Traceback (most recent call last):
  File "C:\Users\Subhasis\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\gui\pairlist.py", line 103, in do_merge
    self.controller.merge_cluster(label_to_merge)
  File "C:\Users\Subhasis\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\gui\cataloguecontroller.py", line 308, in merge_cluster
    self.change_spike_label(mask, new_label)
  File "C:\Users\Subhasis\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\gui\cataloguecontroller.py", line 215, in change_spike_label
    self.cc.change_spike_label(mask, label)
  File "C:\Users\Subhasis\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\catalogueconstructor.py", line 1287, in change_spike_label
    self.pop_labels_from_cluster(to_remove)
  File "C:\Users\Subhasis\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\catalogueconstructor.py", line 1120, in pop_labels_from_cluster
    self.arrays.add_array('clusters', clusters, self.memory_mode)
  File "C:\Users\Subhasis\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\iotools.py", line 147, in add_array
    self.create_array(name, data.dtype, data.shape, memory_mode)
  File "C:\Users\Subhasis\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\iotools.py", line 126, in create_array
    self._check_nb_ref(name)
  File "C:\Users\Subhasis\Anaconda3\envs\spiketutorial\lib\site-packages\tridesclous\iotools.py", line 54, in _check_nb_ref
    assert nb_ref == nb_expect, '{} array is referenced outside {}!={}'.format(name, nb_ref, nb_expect)
AssertionError: clusters array is referenced outside 5!=2

```

**Comment by samuelgarcia** [comment]
Hi @subhacom.

The ability to hack the catalogue with  ipython and see results on cataloguewindow was a an important feature.

What I did, make change in a in a separate ipython and each time a change is done on the catalogue and so on folder then you can use the refresh button that do under the wood a full refresh with full reload from memmap file in folder. I have not tested this since a long time. I hope this is not too buggy.

Playing with attr in the same interpreter as you, I never tested it.  I gues that full referesh should also work. 

tell me.
