### ISSUE TITLE
PermissionError when splitting cluster

### ISSUE THREAD

**Issue by PierreLeCabec** [tridesclous/tridesclous#177]
Hello!

I am trying to split cluster from the catalogue window but I keep on having this traceback:

> Traceback (most recent call last):
  File "C:\Users\Pierre.LE-CABEC\Anaconda3\envs\school_lyon\lib\site-packages\tridesclous\gui\peaklists.py", line 355, in split_selection
    self.controller.split_cluster(label_to_split, method=method,  **kargs) #order_clusters=True,
  File "C:\Users\Pierre.LE-CABEC\Anaconda3\envs\school_lyon\lib\site-packages\tridesclous\gui\cataloguecontroller.py", line 351, in split_cluster
    self.cc.split_cluster(*args,  **kargs)
  File "C:\Users\Pierre.LE-CABEC\Anaconda3\envs\school_lyon\lib\site-packages\tridesclous\catalogueconstructor.py", line 1506, in split_cluster
    self.find_clusters(method=method, selection=mask, **kargs)
  File "C:\Users\Pierre.LE-CABEC\Anaconda3\envs\school_lyon\lib\site-packages\tridesclous\catalogueconstructor.py", line 1166, in find_clusters
    self.delete_waveforms_cache()
  File "C:\Users\Pierre.LE-CABEC\Anaconda3\envs\school_lyon\lib\site-packages\tridesclous\catalogueconstructor.py", line 1037, in delete_waveforms_cache
    self.arrays.delete_array('some_waveforms')
  File "C:\Users\Pierre.LE-CABEC\Anaconda3\envs\school_lyon\lib\site-packages\tridesclous\iotools.py", line 170, in delete_array
    os.remove(filename)
PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\Pierre.LE-CABEC\\Desktop\\tdc_\\channel_group_0\\catalogue_constructor\\some_waveforms.raw'

Rebooting my computer, reinstalling trie des clous on a new environement didn't fix it.

Thanks in advance!

**Comment by samuelgarcia** [comment]
Oups. I will have a look.
