### ISSUE TITLE
examples fail

### ISSUE THREAD

**Issue by whbdupree** [tridesclous/tridesclous#25]
$ python3 example_locust_dataset.py 
Traceback (most recent call last):
  File "example_locust_dataset.py", line 188, in <module>
    extract_waveforms_pca_cluster()
  File "example_locust_dataset.py", line 80, in extract_waveforms_pca_cluster
    catalogueconstructor = CatalogueConstructor(dataio=dataio)
  File "/home/barnett/.local/lib/python3.6/site-packages/tridesclous-0.2.0.dev0-py3.6.egg/tridesclous/catalogueconstructor.py", line 63, in __init__
AttributeError: 'DataIO' object has no attribute 'channel_groups'

I installed with the command `python3 setup.py install --user`

**Comment by whbdupree** [comment]
Also, somebody's home directory is hard coded in the file example_kampff_dataset.py

**Comment by samuelgarcia** [comment]
Thanks I known. tdc is in a process of a big big clean and refactoring.
So some example are broken. I will fix evrything very soon.

**Comment by samuelgarcia** [comment]
Fixed by #26.

I made a small patch to fix kampf example, it should be easier to anderstand.

My guess is that the channel_group was not set correctly. Now the prb file is downloaded automagically.
