### ISSUE TITLE
On Macbook

### ISSUE THREAD

**Issue by samuelgarcia** [tridesclous/tridesclous#30]
Traceback (most recent call last):
  File "/anaconda3/envs/tdc/bin/tdc", line 11, in <module>
    load_entry_point('tridesclous==0.2.0.dev0', 'console_scripts', 'tdc')()
  File "/anaconda3/envs/tdc/lib/python3.6/site-packages/tridesclous/scripts/tdc.py", line 66, in main
    open_mainwindow()
  File "/anaconda3/envs/tdc/lib/python3.6/site-packages/tridesclous/scripts/tdc.py", line 27, in open_mainwindow
    win = tdc.MainWindow()
  File "/anaconda3/envs/tdc/lib/python3.6/site-packages/tridesclous/gui/mainwindow.py", line 46, in __init__
    self.create_actions_and_menu()
  File "/anaconda3/envs/tdc/lib/python3.6/site-packages/tridesclous/gui/mainwindow.py", line 83, in create_actions_and_menu
    self._refresh_recetly_opened()
  File "/anaconda3/envs/tdc/lib/python3.6/site-packages/tridesclous/gui/mainwindow.py", line 148, in _refresh_recetly_opened
    for dirname in self.recently_opened():
  File "/anaconda3/envs/tdc/lib/python3.6/site-packages/tridesclous/gui/mainwindow.py", line 161, in recently_opened
    recently_opened = pickle.loads(value)
TypeError: a bytes-like object is required, not 'str'

**Comment by samuelgarcia** [comment]
clos ed #31
