### ISSUE TITLE
CatalogueWindow crashed with new peaks

### ISSUE THREAD

**Issue by ZeitgeberH** [tridesclous/tridesclous#72]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tridesclous/gui/cataloguewindow.py", line 222, in redetect_peak
    self.refresh()
  File "/usr/local/lib/python3.5/dist-packages/tridesclous/gui/cataloguewindow.py", line 211, in refresh
    w.refresh()
  File "/usr/local/lib/python3.5/dist-packages/tridesclous/gui/featuretimeviewer.py", line 100, in refresh
ValueError: too many values to unpack (expected 1)
Aborted (core dumped)

**Comment by samuelgarcia** [comment]
Thank you for sending the crash.
Could you test with my repo here : https://github.com/samuelgarcia/tridesclous
#71 fix many crash.

**Comment by ZeitgeberH** [comment]
@samuelgarcia your repo solved the issue.Thanks!
