### ISSUE TITLE
tridesclous GUI crashes when opening Plexon data file 

### ISSUE THREAD

**Issue by cuckoong** [tridesclous/tridesclous#99]
After opening the GUI, then File>Initialize dataset>source_type:Plexon>Add file
tried opening .PLX files induced the GUI to crash.

on_addfiles
<class 'tridesclous.datasource.PlexonDataSource'>
multi-file
objc[7328]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8bc2a1d0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1c2d4f7dc8). One of the two will be used. Which one is undefined.
source_params {'filenames': ['/Users/cu/Documents/Jupyter notebook/test/test.plx']}
Traceback (most recent call last):
  File "/Users/cu/anaconda3/envs/SpikeAnalysis/lib/python3.6/site-packages/tridesclous/gui/initializedatasetwindow.py", line 168, in validate_step
    self.display_step('mk_chan_grp')
  File "/Users/cu/anaconda3/envs/SpikeAnalysis/lib/python3.6/site-packages/tridesclous/gui/initializedatasetwindow.py", line 105, in display_step
    channel_names = self.datasource_class(**source_params).get_channel_names()
  File "/Users/cu/anaconda3/envs/SpikeAnalysis/lib/python3.6/site-packages/tridesclous/datasource.py", line 170, in __init__
    assert not rawio._several_channel_groups, 'several sample rate for signals'
AssertionError: several sample rate for signals
Abort trap: 6

I don't know why it said "several sample rate for signals", I only have one sample rate in my file. What should I do with this? Thank you!

**Comment by samuelgarcia** [comment]
This report should be send to https://github.com/NeuralEnsemble/python-neo.
Could you send the file also ?

Plexon make possible to have multiple sampling rate in one file this is not handle with the neo reader.
